language: cpp

matrix:
  include:
    - os: linux
      compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libtesseract-dev
            - libleptonica-dev
          env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      compiler: g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libtesseract-dev
            - libleptonica-dev
          env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      compiler: g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libtesseract-dev
            - libleptonica-dev
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libtesseract-dev
            - libleptonica-dev
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} ..

script: make -j VERBOSE=1 && ARGS=-V make test
